pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        S3_BUCKET = 'jenkins7658'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Deploy to AWS S3') {
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws-credentials-id') {
                    sh '''
                    if ! command -v aws &> /dev/null; then
                        echo "Installing AWS CLI..."
                        sudo apt-get update && sudo apt-get install awscli -y
                    else
                        echo "AWS CLI is already installed."
                    fi
                    
                    aws s3 sync . s3://${S3_BUCKET} --delete
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful!"
        }
        failure {
            echo "❌ Deployment Failed!"
        }
    }
}
